baseURL = "https://janet.blackquill.cc"
defaultContentLanguage = 'en'
title = "Janet Blackquill"
theme = "janet"

[build]
    writeStats = true

[languages]
    [languages.en]
        languageName = 'English'
        weight = 2

    [languages.de]
        languageName = 'Deutsch'
        weight = 1

[menu]

    [[menu.main]]
    identifier = "about"
    name = "about me"
    url = "/"
    weight = -110

    [[menu.main]]
    identifier = "portfolio"
    name = "portfolio"
    url = "/portfolio"
    weight = -100

    [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact"
    weight = -90
